// <auto-generated />
using System;
using Alianza.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alianza.Api.Data.Migraciones
{
    [DbContext(typeof(AlianzaDbContext))]
    partial class AlianzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alianza.Api.Domain.EnlaceRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ambito")
                        .HasColumnType("integer")
                        .HasColumnName("ambito");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plataforma");

                    b.Property<int?>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int?>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_enlaces");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_enlaces_serie_id");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_enlaces_socio_id");

                    b.ToTable("enlaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_enlace_un_propietario", "(serie_id IS NOT NULL AND socio_id IS NULL) OR (serie_id IS NULL AND socio_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Alianza.Api.Domain.EstadoSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_codigo");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.GrupoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos_equipo");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_grupos_equipo_serie_id");

                    b.ToTable("grupos_equipo", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.Medio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alt");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<int?>("SubidoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("subido_por_id");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("Id")
                        .HasName("pk_medios");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_medios_sha256");

                    b.HasIndex("SubidoPorId")
                        .HasDatabaseName("ix_medios_subido_por_id");

                    b.ToTable("medios", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.MedioContenido", b =>
                {
                    b.Property<Guid>("MedioId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_id");

                    b.Property<byte[]>("Datos")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("datos");

                    b.HasKey("MedioId")
                        .HasName("pk_medios_contenido");

                    b.ToTable("medios_contenido", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.MiembroEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_miembros_equipo");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_miembros_equipo_grupo_id");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_miembros_equipo_imagen_id");

                    b.ToTable("miembros_equipo", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.ObraCreador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_obras");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_obras_serie_id");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.PermisoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ambito")
                        .HasColumnType("integer")
                        .HasColumnName("ambito");

                    b.Property<DateTime>("OtorgadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otorgado_en");

                    b.Property<int?>("OtorgadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("otorgado_por_id");

                    b.Property<int?>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_permisos_serie_id");

                    b.HasIndex("UsuarioId", "Ambito", "SerieId")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_usuario_id_ambito_serie_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("UsuarioId", "Ambito", "SerieId"), false);

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorVoz")
                        .HasColumnType("text")
                        .HasColumnName("actor_voz");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid?>("ImagenActorVozId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_actor_voz_id");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.HasKey("Id")
                        .HasName("pk_personajes");

                    b.HasIndex("ImagenActorVozId")
                        .HasDatabaseName("ix_personajes_imagen_actor_voz_id");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_personajes_imagen_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_personajes_serie_id");

                    b.ToTable("personajes", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .HasColumnType("text")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<Guid?>("BannerId")
                        .HasColumnType("uuid")
                        .HasColumnName("banner_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadorDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creador_descripcion");

                    b.Property<Guid?>("CreadorImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_imagen_id");

                    b.Property<string>("CreadorNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("creador_nombre");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid?>("PortadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("portada_id");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean")
                        .HasColumnName("publicada");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sinopsis");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("VideoLocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_local_id");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("BannerId")
                        .HasDatabaseName("ix_series_banner_id");

                    b.HasIndex("CreadorImagenId")
                        .HasDatabaseName("ix_series_creador_imagen_id");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_series_estado_id");

                    b.HasIndex("LogoId")
                        .HasDatabaseName("ix_series_logo_id");

                    b.HasIndex("PortadaId")
                        .HasDatabaseName("ix_series_portada_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_series_slug");

                    b.HasIndex("VideoLocalId")
                        .HasDatabaseName("ix_series_video_local_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.SerieImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alt");

                    b.Property<Guid>("MedioId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_serie_imagenes");

                    b.HasIndex("MedioId")
                        .HasDatabaseName("ix_serie_imagenes_medio_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_serie_imagenes_serie_id");

                    b.ToTable("serie_imagenes", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean")
                        .HasColumnName("publicado");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_socios_imagen_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_socios_slug");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.SocioSerie", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("SocioId", "SerieId")
                        .HasName("pk_socios_series");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_socios_series_serie_id");

                    b.ToTable("socios_series", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("es_super_admin");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_visible");

                    b.Property<int>("Origen")
                        .HasColumnType("integer")
                        .HasColumnName("origen");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PuedeCrearWikis")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_crear_wikis");

                    b.Property<Guid>("SelloSeguridad")
                        .HasColumnType("uuid")
                        .HasColumnName("sello_seguridad");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalizado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username_normalizado");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("EsSuperAdmin")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_un_superadmin")
                        .HasFilter("es_super_admin");

                    b.HasIndex("UsernameNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username_normalizado");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Alianza.Api.Domain.EnlaceRed", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Serie", null)
                        .WithMany("Enlaces")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enlaces_series_serie_id");

                    b.HasOne("Alianza.Api.Domain.Socio", null)
                        .WithMany("Enlaces")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enlaces_socios_socio_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.GrupoEquipo", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Serie", null)
                        .WithMany("Equipo")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_equipo_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Medio", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_medios_usuarios_subido_por_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.MedioContenido", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithOne("Contenido")
                        .HasForeignKey("Alianza.Api.Domain.MedioContenido", "MedioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medios_contenido_medios_medio_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.MiembroEquipo", b =>
                {
                    b.HasOne("Alianza.Api.Domain.GrupoEquipo", null)
                        .WithMany("Miembros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_equipo_grupos_equipo_grupo_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_miembros_equipo_medios_imagen_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.ObraCreador", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Serie", null)
                        .WithMany("ObrasCreador")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obras_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.PermisoUsuario", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_permisos_series_serie_id");

                    b.HasOne("Alianza.Api.Domain.Usuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_usuarios_usuario_id");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Personaje", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenActorVozId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_personajes_medios_imagen_actor_voz_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_personajes_medios_imagen_id");

                    b.HasOne("Alianza.Api.Domain.Serie", null)
                        .WithMany("Personajes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personajes_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Serie", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_banner_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("CreadorImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_creador_imagen_id");

                    b.HasOne("Alianza.Api.Domain.EstadoSerie", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_estados_estado_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_logo_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("PortadaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_portada_id");

                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("VideoLocalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_video_local_id");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Alianza.Api.Domain.SerieImagen", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("MedioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_serie_imagenes_medios_medio_id");

                    b.HasOne("Alianza.Api.Domain.Serie", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serie_imagenes_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Socio", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_socios_medios_imagen_id");
                });

            modelBuilder.Entity("Alianza.Api.Domain.SocioSerie", b =>
                {
                    b.HasOne("Alianza.Api.Domain.Serie", "Serie")
                        .WithMany("Socios")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_series_series_serie_id");

                    b.HasOne("Alianza.Api.Domain.Socio", "Socio")
                        .WithMany("Series")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_series_socios_socio_id");

                    b.Navigation("Serie");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Alianza.Api.Domain.GrupoEquipo", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Medio", b =>
                {
                    b.Navigation("Contenido")
                        .IsRequired();
                });

            modelBuilder.Entity("Alianza.Api.Domain.Serie", b =>
                {
                    b.Navigation("Enlaces");

                    b.Navigation("Equipo");

                    b.Navigation("Imagenes");

                    b.Navigation("ObrasCreador");

                    b.Navigation("Personajes");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Socio", b =>
                {
                    b.Navigation("Enlaces");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Alianza.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
