// <auto-generated />
using System;
using System.Collections.Generic;
using Alianza.Servidor.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alianza.Servidor.Datos.Migraciones
{
    [DbContext(typeof(BaseDeDatos))]
    partial class BaseDeDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alianza.Servidor.Datos.BloqueoIp", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("Hasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hasta");

                    b.Property<bool>("Manual")
                        .HasColumnType("boolean")
                        .HasColumnName("manual");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<int>("Veces")
                        .HasColumnType("integer")
                        .HasColumnName("veces");

                    b.HasKey("Ip")
                        .HasName("pk_bloqueos_ip");

                    b.ToTable("bloqueos_ip", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ContenidoMedio", b =>
                {
                    b.Property<Guid>("MedioId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_id");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.HasKey("MedioId")
                        .HasName("pk_contenidos_medio");

                    b.ToTable("contenidos_medio", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Enlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plataforma");

                    b.Property<int?>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int?>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("Uso")
                        .HasColumnType("integer")
                        .HasColumnName("uso");

                    b.HasKey("Id")
                        .HasName("pk_enlaces");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_enlaces_serie_id");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_enlaces_socio_id");

                    b.ToTable("enlaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_enlace_un_dueno", "(serie_id IS NOT NULL AND socio_id IS NULL) OR (serie_id IS NULL AND socio_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.EnlaceSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plataforma");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_enlaces_sitio");

                    b.ToTable("enlaces_sitio", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.EstadoSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_codigo");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.EventoSeguridad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Gravedad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gravedad");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<bool>("Revisado")
                        .HasColumnType("boolean")
                        .HasColumnName("revisado");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ruta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Usuario")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_eventos_seguridad");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_eventos_seguridad_fecha");

                    b.HasIndex("Ip")
                        .HasDatabaseName("ix_eventos_seguridad_ip");

                    b.HasIndex("Gravedad", "Revisado")
                        .HasDatabaseName("ix_eventos_seguridad_gravedad_revisado");

                    b.ToTable("eventos_seguridad", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.GrupoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.HasKey("Id")
                        .HasName("pk_grupo_equipo");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_grupo_equipo_serie_id");

                    b.ToTable("grupo_equipo", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ImagenSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("MedioId")
                        .HasColumnType("uuid")
                        .HasColumnName("medio_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<string>("TextoAlternativo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_alternativo");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_imagenes_serie");

                    b.HasIndex("MedioId")
                        .HasDatabaseName("ix_imagenes_serie_medio_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_imagenes_serie_serie_id");

                    b.ToTable("imagenes_serie", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Medio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("huella");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<DateTime>("SubidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subido_en");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano");

                    b.Property<string>("TextoAlternativo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_alternativo");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("Id")
                        .HasName("pk_medios");

                    b.HasIndex("Huella")
                        .IsUnique()
                        .HasDatabaseName("ix_medios_huella");

                    b.ToTable("medios", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.MiembroEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_miembros_equipo");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_miembros_equipo_grupo_id");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_miembros_equipo_imagen_id");

                    b.ToTable("miembros_equipo", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ObraCreador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_obra_creador");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_obra_creador_serie_id");

                    b.ToTable("obra_creador", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("integer")
                        .HasColumnName("area");

                    b.Property<int?>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_permisos_serie_id");

                    b.HasIndex("UsuarioId", "Area", "SerieId")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_usuario_id_area_serie_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("UsuarioId", "Area", "SerieId"), false);

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorVoz")
                        .HasColumnType("text")
                        .HasColumnName("actor_voz");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid?>("ImagenActorVozId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_actor_voz_id");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.HasKey("Id")
                        .HasName("pk_personajes");

                    b.HasIndex("ImagenActorVozId")
                        .HasDatabaseName("ix_personajes_imagen_actor_voz_id");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_personajes_imagen_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_personajes_serie_id");

                    b.ToTable("personajes", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Postulacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("RecibidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibida_en");

                    b.HasKey("Id")
                        .HasName("pk_postulaciones");

                    b.HasIndex("Estado", "RecibidaEn")
                        .HasDatabaseName("ix_postulaciones_estado_recibida_en");

                    b.ToTable("postulaciones", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Ayuda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ayuda");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatoria");

                    b.Property<List<string>>("Opciones")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("opciones");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_preguntas");

                    b.ToTable("preguntas", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Respuesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("PostulacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("postulacion_id");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pregunta");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_respuesta");

                    b.HasIndex("PostulacionId")
                        .HasDatabaseName("ix_respuesta_postulacion_id");

                    b.ToTable("respuesta", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid?>("CabeceraId")
                        .HasColumnType("uuid")
                        .HasColumnName("cabecera_id");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("CreadorDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creador_descripcion");

                    b.Property<Guid?>("CreadorImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_imagen_id");

                    b.Property<string>("CreadorNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creador_nombre");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificador");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid?>("PortadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("portada_id");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean")
                        .HasColumnName("publicada");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sinopsis");

                    b.Property<string>("UrlVideo")
                        .HasColumnType("text")
                        .HasColumnName("url_video");

                    b.Property<Guid?>("VideoPropioId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_propio_id");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("CabeceraId")
                        .HasDatabaseName("ix_series_cabecera_id");

                    b.HasIndex("CreadorImagenId")
                        .HasDatabaseName("ix_series_creador_imagen_id");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_series_estado_id");

                    b.HasIndex("Identificador")
                        .IsUnique()
                        .HasDatabaseName("ix_series_identificador");

                    b.HasIndex("LogoId")
                        .HasDatabaseName("ix_series_logo_id");

                    b.HasIndex("PortadaId")
                        .HasDatabaseName("ix_series_portada_id");

                    b.HasIndex("VideoPropioId")
                        .HasDatabaseName("ix_series_video_propio_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificador");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid")
                        .HasColumnName("imagen_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean")
                        .HasColumnName("publicado");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.HasIndex("Identificador")
                        .IsUnique()
                        .HasDatabaseName("ix_socios_identificador");

                    b.HasIndex("ImagenId")
                        .HasDatabaseName("ix_socios_imagen_id");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.SocioSerie", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("SocioId", "SerieId")
                        .HasName("pk_socios_series");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_socios_series_serie_id");

                    b.ToTable("socios_series", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.TextoSitio", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Clave")
                        .HasName("pk_textos_sitio");

                    b.ToTable("textos_sitio", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsSuperadmin")
                        .HasColumnType("boolean")
                        .HasColumnName("es_superadmin");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("NombreUsuarioNormalizado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario_normalizado");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_visible");

                    b.Property<int>("Origen")
                        .HasColumnType("integer")
                        .HasColumnName("origen");

                    b.Property<bool>("PuedeCrearWikis")
                        .HasColumnType("boolean")
                        .HasColumnName("puede_crear_wikis");

                    b.Property<Guid>("SelloSesion")
                        .HasColumnType("uuid")
                        .HasColumnName("sello_sesion");

                    b.Property<string>("UltimaIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ultima_ip");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("EsSuperadmin")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_un_superadmin")
                        .HasFilter("es_superadmin");

                    b.HasIndex("NombreUsuarioNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_nombre_usuario_normalizado");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ContenidoMedio", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithOne("Contenido")
                        .HasForeignKey("Alianza.Servidor.Datos.ContenidoMedio", "MedioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contenidos_medio_medios_medio_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Enlace", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Serie", null)
                        .WithMany("Enlaces")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enlaces_series_serie_id");

                    b.HasOne("Alianza.Servidor.Datos.Socio", null)
                        .WithMany("Enlaces")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enlaces_socios_socio_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.GrupoEquipo", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Serie", null)
                        .WithMany("Equipo")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupo_equipo_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ImagenSerie", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("MedioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imagenes_serie_medios_medio_id");

                    b.HasOne("Alianza.Servidor.Datos.Serie", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imagenes_serie_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.MiembroEquipo", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.GrupoEquipo", null)
                        .WithMany("Miembros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_equipo_grupo_equipo_grupo_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_miembros_equipo_medios_imagen_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.ObraCreador", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Serie", null)
                        .WithMany("ObrasCreador")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_obra_creador_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Permiso", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_permisos_series_serie_id");

                    b.HasOne("Alianza.Servidor.Datos.Usuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_usuarios_usuario_id");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Personaje", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenActorVozId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_personajes_medios_imagen_actor_voz_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_personajes_medios_imagen_id");

                    b.HasOne("Alianza.Servidor.Datos.Serie", null)
                        .WithMany("Personajes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personajes_series_serie_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Respuesta", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Postulacion", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respuesta_postulaciones_postulacion_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Serie", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("CabeceraId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_cabecera_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("CreadorImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_creador_imagen_id");

                    b.HasOne("Alianza.Servidor.Datos.EstadoSerie", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_estados_estado_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_logo_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("PortadaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_portada_id");

                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("VideoPropioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_series_medios_video_propio_id");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Socio", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Medio", null)
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_socios_medios_imagen_id");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.SocioSerie", b =>
                {
                    b.HasOne("Alianza.Servidor.Datos.Serie", "Serie")
                        .WithMany("Socios")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_series_series_serie_id");

                    b.HasOne("Alianza.Servidor.Datos.Socio", "Socio")
                        .WithMany("Series")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_series_socios_socio_id");

                    b.Navigation("Serie");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.GrupoEquipo", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Medio", b =>
                {
                    b.Navigation("Contenido")
                        .IsRequired();
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Postulacion", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Serie", b =>
                {
                    b.Navigation("Enlaces");

                    b.Navigation("Equipo");

                    b.Navigation("Imagenes");

                    b.Navigation("ObrasCreador");

                    b.Navigation("Personajes");

                    b.Navigation("Socios");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Socio", b =>
                {
                    b.Navigation("Enlaces");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Alianza.Servidor.Datos.Usuario", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
